### PR TITLE
Master uavcan for flow

### PR DESCRIPTION
**Pull request by davids5**
@tcauchois , @kevinmehall  

This PR brings the module uavcan up to date with upstream beta

Then adds the Uavcan Time Synchronization functionality so that the px4fmu will act as the master clock.

Since the master branch herein is relatively old I backported in the distance sensor uOrb
and finally have wired in uavcan to publish <UAVCAN>--<uOrb> for flow and range.

N.B. flow is the the Legacy I2c data. 1110.LegacyRawSample.uavcan should not be released, (if it is the DSDL ID (1110)  should be changed to a value based off of 16384  as it (1110) is currently in the uavcan reserved range

@LorenzMeier Please review the uavcan to uORB transforms - in flow.cpp and range.cpp (is most likely wrong)

Until the messaging is settled down this should get Daniel something to work with.

### CODE REVIEW

**Comment by johnnyman727** [comment]
:clap: :clap:

**Comment by kevinmehall** [comment]
I was able to get this to build and synchronize time with a PX4Flow.

It required some changes to work around build errors:

In the toplevel `solo/uavcan` directory, check out the same version of libuavcan as `PX4Firmware/src/lib/uavcan` -- I'm not sure why `uavcan` is a submodule of `solo` directly, and any paths that reference it should probably be changed to point to the submodule under PX4Firmware.

---

```
/Users/kevinmehall/GitHub/solo/ardupilot-solo/libraries/AP_NavEKF/AP_NavEKF.cpp:
In member function 'void NavEKF::CovariancePrediction()':
/Users/kevinmehall/GitHub/solo/ardupilot-solo/libraries/AP_NavEKF/AP_NavEKF.cpp:1882:1:
error: the frame size of 2256 bytes is larger than 1024 bytes [-Werror=frame-larger-than=]
 }
 ^
```

px4firmware patch:
```.diff
diff --git a/makefiles/toolchain_gnu-arm-eabi.mk b/makefiles/toolchain_gnu-arm-eabi.mk
index 7804a42..0be6653 100644
--- a/makefiles/toolchain_gnu-arm-eabi.mk
+++ b/makefiles/toolchain_gnu-arm-eabi.mk
@@ -132,7 +132,7 @@ ARCHCXXFLAGS      = -fno-exceptions -fno-rtti -std=gnu++0x -fno-threadsafe-statics
 
 #
 # Provide defaults, but allow for module override
-WFRAME_LARGER_THAN ?= 1024
+WFRAME_LARGER_THAN ?= 4096
 
 
 

```

---

```
/Users/kevinmehall/GitHub/solo/PX4Firmware/src/lib/uavcan/libuavcan_drivers/stm32/driver/src/uc_stm32_clock.cpp:358:18:
error: 'abs' is not a member of 'std'
                 (std::abs(utc_rel_rate_ppm) < utc_sync_params.lock_thres_rate_ppm) &&
                  ^
```

uavcan patch:
```.diff
diff --git a/libuavcan_drivers/stm32/driver/src/uc_stm32_clock.cpp b/libuavcan_drivers/stm32/driver/src/uc_stm32_clock.cpp
index b54bf1b..76e20b3 100644
--- a/libuavcan_drivers/stm32/driver/src/uc_stm32_clock.cpp
+++ b/libuavcan_drivers/stm32/driver/src/uc_stm32_clock.cpp
@@ -355,8 +355,8 @@ void adjustUtc(uavcan::UtcDuration adjustment)
         if (!utc_locked)
         {
             utc_locked =
-                (std::abs(utc_rel_rate_ppm) < utc_sync_params.lock_thres_rate_ppm) &&
-                (std::abs(utc_prev_adj) < utc_sync_params.lock_thres_offset.toUSec());
+                (std::fabs(utc_rel_rate_ppm) < utc_sync_params.lock_thres_rate_ppm) &&
+                (std::fabs(utc_prev_adj) < utc_sync_params.lock_thres_offset.toUSec());
         }
     }
 }
@@ -444,7 +444,7 @@ UAVCAN_STM32_IRQ_HANDLER(TIMX_IRQHandler)
     {
         time_utc += USecPerOverflow;
         utc_accumulated_correction_nsec += utc_correction_nsec_per_overflow;
-        if (std::abs(utc_accumulated_correction_nsec) >= 1000)
+        if (std::fabs(utc_accumulated_correction_nsec) >= 1000)
         {
             time_utc = uavcan::uint64_t(uavcan::int64_t(time_utc) + utc_accumulated_correction_nsec / 1000);
             utc_accumulated_correction_nsec %= 1000;
```

**Comment by tcauchois** [comment]
The reason there's a top-level uavcan directory is that other solo software (sololink, flow, etc) will all want to use the same uavcan version, and having a master repo facilitates that.  How much of a hassle is it to make px4firmware look for uavcan in the top-level directory?

**Comment by davids5** [comment]
@kevinmehall  

RE:/makefiles/toolchain_gnu-arm-eabi.mk  

It is advisable to keep this tight - It will save all of US from accidental local defs that are too big.

The better approch is to set WFRAME_LARGER_THAN in the moulde.mk file of the offending module 

See https://github.com/PX4/Firmware/blob/nuttx_next/makefiles/nuttx/toolchain_gnu-arm-eabi.mk#L148-L158 and https://github.com/PX4/Firmware/blob/4aec25724e92bf4b80780336fc2313d2aad3736c/src/modules/uavcan/module.mk#L43

RE:uavcan location <>/uavcan is legacy. To fix this I think you just have to update the setup.mk https://github.com/3drobotics/PX4Firmware-solo/blob/master/makefiles/setup.mk#L53 
and Tools/ https://github.com/3drobotics/PX4Firmware-solo/blob/master/Tools/check_submodules.sh#L55

RE: uavcan patch: The proper fix was added in upstream nuttx  https://github.com/PX4-NuttX/nuttx/blob/last_nuttx_next/include/cxx/cstdlib#L105

**Pull request closed without merging**
